name: Build and Push Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set short SHA
      id: short-sha
      run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Set image name
      id: image-name
      run: echo "IMAGE_NAME=adventure_log_frontend" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} # Use CR_PAT if you're using a Personal Access Token

    - name: Build frontend Docker image
      run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }} ./frontend

    - name: Tag frontend Docker Image
      run: docker tag ${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }} ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}
    
    - name: Push frontend Docker Image
      run: docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}

