name: Build and Push Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set short SHA
      id: short-sha
      run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} # Use CR_PAT if you're using a Personal Access Token

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./frontend/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/adventure_log_frontend:${{ env.SHORT_SHA }}
    
    - name: Build and push backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./backend/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/adventure_log_backend:${{ env.SHORT_SHA }}

