name: Build and Push Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set short SHA
      id: short-sha
      run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} # Use CR_PAT if you're using a Personal Access Token

    - name: Build frontend Docker image
      run: docker build -t frontend:${{ env.SHORT_SHA }} ./frontend

    - name: Tag frontend Docker Image
      run: docker tag frontend:${{ env.SHORT_SHA }} ghcr.io/${{ github.repository_owner }}/frontend:${{ env.SHORT_SHA }}
    
    - name: Push frontend Docker Image
      run: docker push ghcr.io/${{ github.repository_owner }}/frontend:${{ env.SHORT_SHA }}
    
    - name: Build backend Docker image
      run: docker build -t backend:${{ env.SHORT_SHA }} ./backend

    - name: Tag backend Docker Image
      run: docker tag backend:${{ env.SHORT_SHA }} ghrc.io/${{ github.repository_owner }}/backend:${{ env.SHORT_SHA }}

    - name: Push backend Docker Image
      run: docker push ghcr.io/${{ github.repository_owner }}/backend:${{ env.SHORT_SHA }}
